version = 1

test_patterns = ["*/test/**"]

exclude_patterns = [
  "public/**",
  "dist/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  environment = ["browser", "nodejs"]
  module_system = "es-modules"
  dialect = "typescript"
  style_guide = "standard"
  skip_doc_coverage = ["class-expression", "method-definition", "arrow-function-expression"]

