version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  environment = ["browser", "nodejs"]
  module_system = "es-modules"
  dialect = "typescript"
  style_guide = "standard"
